### ISSUE TITLE
I tried to use this - but it returns an ERROR (command 'converter.encode' was not found )

### ISSUE THREAD

**Issue by Dr-Bones2** [ziloen/html-entities-converter#3]
I want to be able to convert something like this: └─────┬─────┘ into this: &#9492;&#9472;&#9472;&#9472;&#9472;&#9472;&#9516;&#9472;&#9472;&#9472;&#9472;&#9472;&#9496;
I thought this might work...
But it just retyurned an error
![vs-html-converter](https://user-images.githubusercontent.com/111000259/183974065-02566187-f4b8-4c94-ba94-183b24e9aee9.jpg)

**Comment by ziloen** [comment]
@Dr-Bones2 Should been fixed in 0.0.7
